"use client";

import * as React from "react";
import Link from "next/link";
import { Sparkles, Loader2, AlertTriangle, ArrowRight, RefreshCw } from "lucide-react";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import type { ScanResult } from "@/lib/risk-engine/types";
import type { AiReport, AiReportResponse } from "@/lib/ai-report/types";
import { getAiReport, saveAiReport } from "@/lib/ai-report/storage";

export function AiReportSection({ scan }: { scan: ScanResult }) {
  const [report, setReport] = React.useState<AiReport | null>(null);
  const [source, setSource] = React.useState<"deepseek" | "fallback" | null>(null);
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const [mounted, setMounted] = React.useState(false);

  React.useEffect(() => {
    setMounted(true);
    const existing = getAiReport(scan.scanId);
    if (existing) {
      setReport(existing);
      setSource(existing.provider === "deepseek" ? "deepseek" : "fallback");
    }
  }, [scan.scanId]);

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/reports/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ scanResult: scan }),
      });
      const data = (await res.json()) as AiReportResponse | { error?: string };
      if (!res.ok || !("aiReport" in data)) {
        setError(("error" in data && data.error) || "Failed to generate report.");
        return;
      }
      saveAiReport(scan.scanId, data.aiReport);
      setReport(data.aiReport);
      setSource(data.source);
    } catch {
      setError("Network error. Could not reach the report service.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <Card className="p-6">
      <div className="flex items-center gap-2">
        <Sparkles className="h-5 w-5 text-blue-600" />
        <h2 className="font-display font-bold text-slate-900">AI Risk Report</h2>
        {mounted && source && (
          <Badge tone={source === "deepseek" ? "brand" : "neutral"} className="ml-auto">
            {source === "deepseek" ? "Generated by DeepSeek" : "Fallback Report"}
          </Badge>
        )}
      </div>

      {!report ? (
        <>
          <p className="mt-3 text-sm text-slate-500">
            Generate a structured, plain-language report that explains the
            deterministic findings above. This is automated risk intelligence,
            not a formal audit.
          </p>
          {error && (
            <div className="mt-3 flex items-start gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-600">
              <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
              <span>{error}</span>
            </div>
          )}
          <Button className="mt-4" onClick={generate} disabled={loading}>
            {loading ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" /> Generating…
              </>
            ) : (
              <>
                <Sparkles className="h-4 w-4" /> Generate AI Report
              </>
            )}
          </Button>
        </>
      ) : (
        <>
          <p className="mt-3 text-sm leading-relaxed text-slate-600">
            {report.executiveSummary}
          </p>
          <div className="mt-4 flex flex-wrap items-center gap-3">
            <Link href={`/reports/${scan.scanId}`}>
              <Button size="sm">
                View full report <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
            <button
              type="button"
              onClick={generate}
              disabled={loading}
              className="inline-flex items-center gap-1.5 text-xs font-medium text-slate-500 hover:text-slate-800 disabled:opacity-50"
            >
              {loading ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
              ) : (
                <RefreshCw className="h-3.5 w-3.5" />
              )}
              Regenerate
            </button>
          </div>
          <p className="mt-3 text-[11px] text-slate-400">{report.disclaimer}</p>
        </>
      )}
    </Card>
  );
}
