"use client";

import * as React from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import {
  Sparkles,
  Target,
  ListChecks,
  ClipboardList,
  Wrench,
  Info,
  FileText,
} from "lucide-react";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { getAiReport } from "@/lib/ai-report/storage";
import type { AiReport } from "@/lib/ai-report/types";
import { severityToTone } from "@/lib/risk-engine/ui";

export function AiReportView() {
  const params = useParams<{ id: string }>();
  const id = params?.id ?? "";
  const [report, setReport] = React.useState<AiReport | null>(null);
  const [mounted, setMounted] = React.useState(false);

  React.useEffect(() => {
    setMounted(true);
    setReport(getAiReport(id));
  }, [id]);

  if (!mounted) {
    return (
      <Card className="p-6 text-sm text-slate-400">Loading report…</Card>
    );
  }

  if (!report) {
    return (
      <Card className="p-8 text-center">
        <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-100">
          <FileText className="h-6 w-6 text-slate-400" />
        </div>
        <h2 className="mt-4 font-display text-lg font-bold text-slate-900">
          AI report has not been generated yet.
        </h2>
        <p className="mt-2 text-sm text-slate-500">
          Run the scan and generate the AI report from the scan result page.
        </p>
        <Link href={`/scan/${id}`} className="mt-5 inline-block">
          <Button>
            <Sparkles className="h-4 w-4" /> Go to scan result
          </Button>
        </Link>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      {/* Executive summary */}
      <Card className="p-6">
        <SectionTitle icon={Target} title="Executive Summary">
          <Badge
            tone={report.provider === "deepseek" ? "brand" : "neutral"}
            className="ml-auto"
          >
            {report.provider === "deepseek" ? "Generated by DeepSeek" : "Fallback Report"}
          </Badge>
        </SectionTitle>
        <p className="mt-3 text-sm leading-relaxed text-slate-600">
          {report.executiveSummary}
        </p>
        <p className="mt-4 border-t border-slate-200 pt-3 text-sm leading-relaxed text-slate-600">
          {report.riskExplanation}
        </p>
      </Card>

      {/* Key findings */}
      {report.keyFindings.length > 0 && (
        <Card className="p-6">
          <SectionTitle icon={ListChecks} title="Key Findings" />
          <div className="mt-4 space-y-4">
            {report.keyFindings.map((f, i) => (
              <div
                key={`${f.title}-${i}`}
                className="rounded-xl border border-slate-200 bg-slate-50/60 p-4"
              >
                <div className="flex items-center gap-2">
                  <span className="text-sm font-semibold text-slate-900">
                    {f.title}
                  </span>
                  <Badge tone={severityToTone(f.severity)} className="ml-auto">
                    {f.severity}
                  </Badge>
                </div>
                {f.explanation && (
                  <p className="mt-2 text-sm text-slate-600">{f.explanation}</p>
                )}
                {f.evidence && (
                  <p className="mt-1.5 text-xs text-slate-500">
                    <span className="text-slate-400">Evidence:</span>{" "}
                    <span className="font-mono">{f.evidence}</span>
                  </p>
                )}
                {f.recommendation && (
                  <p className="mt-1.5 text-xs text-blue-700">
                    <span className="font-semibold">Recommendation:</span>{" "}
                    {f.recommendation}
                  </p>
                )}
              </div>
            ))}
          </div>
        </Card>
      )}

      {/* Recommended actions */}
      {report.recommendedActions.length > 0 && (
        <Card className="p-6">
          <SectionTitle icon={ClipboardList} title="Recommended Actions" />
          <ul className="mt-4 space-y-2.5">
            {report.recommendedActions.map((a, i) => (
              <li key={i} className="flex items-start gap-2.5 text-sm text-slate-600">
                <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-blue-500" />
                {a}
              </li>
            ))}
          </ul>
        </Card>
      )}

      {/* Technical notes */}
      {report.technicalNotes && (
        <Card className="p-6">
          <SectionTitle icon={Wrench} title="Technical Notes" />
          <p className="mt-3 text-sm leading-relaxed text-slate-600">
            {report.technicalNotes}
          </p>
        </Card>
      )}

      {/* Limitations */}
      {report.limitations.length > 0 && (
        <Card className="p-6">
          <SectionTitle icon={Info} title="Limitations" />
          <ul className="mt-4 space-y-2.5">
            {report.limitations.map((l, i) => (
              <li key={i} className="flex items-start gap-2.5 text-sm text-slate-600">
                <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-slate-300" />
                {l}
              </li>
            ))}
          </ul>
        </Card>
      )}

      {/* Disclaimer */}
      <div className="rounded-2xl border border-blue-200 bg-blue-50 p-5 text-sm leading-relaxed text-slate-600">
        {report.disclaimer}
      </div>
    </div>
  );
}

function SectionTitle({
  icon: Icon,
  title,
  children,
}: {
  icon: React.ElementType;
  title: string;
  children?: React.ReactNode;
}) {
  return (
    <div className="flex items-center gap-2">
      <Icon className="h-5 w-5 text-blue-600" />
      <h2 className="font-display font-bold text-slate-900">{title}</h2>
      {children}
    </div>
  );
}
